version: '2'

services:
  db:
      container_name: django-basic-db-container
      build:
          context: ./docker/development/db
          args:
              HOST_UID: ${HOST_UID}
      volumes:
          - ./docker/volumes/db:/var/lib/postgresql/data
      environment:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: django_blog
          POSTGRES_DB: django_blog
          PGDATA: /var/lib/postgresql/data/pgdata
      restart: always

  manage:
      build:
          context: .
          dockerfile: docker/development/web/Dockerfile
      entrypoint: python manage.py
      volumes:
          - ./:/code/

  web:
      container_name: django-basic-web-container
      extends:
          service: manage
      command: runserver 0.0.0.0:8000
      ports:
          - "8000:8000"
      depends_on:
          - db
      links:
          - db
      restart: always