# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import project.apps.cms.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('slug', models.SlugField(help_text="Used to build the entry's URL.", max_length=255, verbose_name='slug')),
                ('meta_title', models.CharField(max_length=255, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='meta description')),
                ('meta_keywords', models.TextField(blank=True, max_length=255, null=True, verbose_name='meta keywords')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=project.apps.cms.enums.Status(1), verbose_name='status')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
            ],
        ),
    ]
