# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170512_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.CharField(max_length=255, null=True, verbose_name='meta description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(max_length=255, null=True, verbose_name='meta keywords'),
        ),
    ]
