# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20170512_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='meta description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_keywords',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='meta keywords'),
        ),
    ]
